### ISSUE TITLE
How to reproduce results in the paper?

### ISSUE THREAD

**Issue by tonygracious** [zyli93/PDER#1]
Could you please add the parameters and the datasets required required to reproduce the results in your paper?

**Comment by JasonYang8119** [comment]
cannot reproduce codes:

I have tried to uncomment these codes behind of preprocessing.py, and run it by `python src/preprocessing.py english 5 0.1 20`

```
    # Split contest to question and answer
    print("\tSpliting post")
    split_post(raw_dir=RAW_DIR, data_dir=DATA_DIR)

    # Extract question-user, answer-user, and question-answer information
    # Generate Question and Answer/User map
    print("\tProcessing QA")
    process_QA(data_dir=DATA_DIR)

    print("\tGenerating question statistics...")
    question_stats(data_dir=DATA_DIR)

    print("\tExtracting question content ...")
    extract_question_content(data_dir=DATA_DIR, parsed_dir=PARSED_DIR)

    print("\tBuilding test sets")
    build_test_set(data_dir=DATA_DIR, parsed_dir=PARSED_DIR,
                    threshold=threshold, test_sample_size=sample_size,
                    test_proportion=prop_test)

    print("\tExtracting Q, R, A relations ...")
    extract_question_user(data_dir=DATA_DIR, parsed_dir=PARSED_DIR)

    extract_question_answer_user(data_dir=DATA_DIR, parsed_dir=PARSED_DIR)


    extract_answer_score(data_dir=DATA_DIR, parsed_dir=PARSED_DIR)
    extract_question_best_answerer_2(data_dir=DATA_DIR, parsed_dir=PARSED_DIR)

    write_part_users(parsed_dir=PARSED_DIR)

    print("Done!")
```

then generate_walk.py can be run without any changed, which is `python src/generate_walk.py english 13 20 4`. But at last `run src/run.sh`, there are some errors:

Before I used this command `sh run.sh 0 english 111 20 13` , I have changed the parameters in `run.sh`. The parameters are the same as your article settings, then there came errors

```
Done - Data Loader!
40779
vocab_size 40780
Using device 0
Traceback (most recent call last):
  File "src/main.py", line 197, in <module>
    runPDER(options)
  File "src/main.py", line 58, in runPDER
    pder_model.run()
  File "/home/yangjie/workplace/NeRank/src/pder.py", line 103, in run
    neg_ratio=self.neg_sample_ratio)
  File "/home/yangjie/workplace/NeRank/src/data_loader.py", line 170, in get_train_batch
    aqr, accqr = self.get_answer_sample(upos, self.ANS_SAMPLE_SIZE)
  File "/home/yangjie/workplace/NeRank/src/data_loader.py", line 237, in get_answer_sample
    aids += self.q2a[qid]
KeyError: 47667
```

Btw, when I use the `generate_metapaths()`method in `src/gnerate_walk.py`, which is generated random walk by meta_pattern `ARQRA`, there are also some errors:

```
Traceback (most recent call last):
  File "src/generate_walk.py", line 362, in <module>
    gw.generate_metapaths(patterns=["AQRQA"], alpha=0)
  File "src/generate_walk.py", line 141, in generate_metapaths
    pattern=meta_pattern))
  File "src/generate_walk.py", line 252, in __meta_path_walk
    next_node = rand.choice(possible_next_node)
  File "/home/yangjie/anaconda3/envs/pytorch/lib/python3.6/random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

It means there are no next_node in `__meta_path_walk(self, start=None, alpha=0.0, pattern=None)` method:

```
possible_next_node = [neighbor
                      for neighbor in G.neighbors(cur_node)
                      if type_of(neighbor) == pattern[pat_ind]]
```

so, could you please give us some more tutorial to reproduce your article?

Besides,  the parameters in `src/preprocessing.py`,  which are`[threshold]` and `[test sample size]`, could you give more information about then. couse I have not seen then in your articles.

**Comment by Cloudcatcher888** [comment]
hello, have you reproduced the result?

**Comment by lzql1zq** [comment]
Hello, Have you solved the problem yet?

**Comment by lzql1zq** [comment]
I have solved the problem. The reason is that the `Q_R.txt` file produced by `preprocessing.py` contains the ID of users that do not exist in the `Q_A.txt`. This causes errors when running `gnerate_walk.py` and `run src/run.sh`. The solution is to comment `INPUT = "Record_Train.json"` in `preprocessing.py` and uncomment` INPUT = "Record_All.json"`.

**Comment by lzql1zq** [comment]
I have solved the problem. The reason is that the `Q_R.txt` file produced by `preprocessing.py` contains the ID of users that do not exist in the `Q_A.txt`. This causes errors when running `gnerate_walk.py` and `run src/run.sh`. The solution is to comment `INPUT = "Record_All.json"` in `preprocessing.py` and uncomment` INPUT = "Record_Train.json"`.
